#!/usr/bin/env ruby

#######################################################################
##                        <http://lisaac.org>                        ##
##                       Lisaac  Coverage Tool                       ##
##                                                                   ##
##                LSIIT - ULP - CNRS - INRIA - FRANCE                ##
##                                                                   ##
#######################################################################
## Copyright (c) 2010 Mildred Ki'Lya <mildred593(at)online.fr>
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal in the Software without
## restriction, including without limitation the rights to use,
## copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following
## conditions:
##
## The above copyright notice and this permission notice shall be
## included in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
## EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
## OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
## NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
## HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
## WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
## OTHER DEALINGS IN THE SOFTWARE.
#######################################################################

require 'optparse'
require 'ostruct'
require 'pp'
require 'fileutils'
require 'erb'

options = OpenStruct.new
options.excludes = []
options.html = false
options.output = "."
options.verbose = false

opts = OptionParser.new do |opts|
  opts.banner = "Usage: licov [options]"

  opts.separator ""
  opts.separator "Specific options:"

  opts.on("-e", "--exclude PATTERN", "Exclude files matching PATTERN") do |pattern|
    options.excludes << Regexp.new(pattern)
  end

  opts.on("--html", "Generate HTML report") do
    options.html = true
  end

  opts.on("-o", "--output DIR", "Select output directory DIR for HTML generation") do |dir|
    options.output = dir
  end

  opts.separator ""
  opts.separator "Common options:"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options.verbose = v
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end

  opts.on_tail("--version", "Show version") do
    puts OptionParser::Version.join('.')
    exit
  end
end

class CovList
  attr_reader :file
  attr_reader :coords
  attr_reader :line_start
  attr_reader :col_start
  attr_reader :line_end
  attr_reader :col_end
  attr_reader :covered
  attr_reader :dead

  def initialize(file, coords)
    m = coords.match /^([0-9]+):([0-9]+):([0-9]+):([0-9]+)$/
    @coords     = m[0]
    @line_start = m[1].to_i - 1
    @col_start  = m[2].to_i
    @line_end   = m[3].to_i - 1
    @col_end    = m[4].to_i
    @covered    = 0
    @dead       = true
    @file       = file
  end
  
  def add_coverage(num)
    @covered += num
    @dead     = false
  end
  
  def dead?
    dead
  end
  
  def covered?
    covered > 0
  end
end

class CovFile
  attr_accessor :name
  attr_accessor :url
  attr_reader :info
  attr_reader :file_name
  attr_reader :num_lists
  attr_reader :num_covered
  attr_reader :num_dead
  
  def initialize(parent, name)
    
    if File.respond_to?(:realpath) then
      @file_name = File.realpath(name)
    else
      @file_name = File.expand_path(name)
    end
    @lists = {}
    @info = parent
  end
  
  def <=> (other)
    percent_covered <=> other.percent_covered
  end
  
  def lists
    @lists.values
  end
  
  def list(coords)
    if @lists[coords].nil? then
      #puts "LIST:#{file_name}:#{coords}"
      @lists[coords] = CovList.new(self, coords)
    else
      @lists[coords]
    end
  end
  
  def compute
    @num_lists   = lists.count
    @num_covered = 0
    @num_dead    = 0
    lists.each do |l|
      @num_covered += (l.covered > 0) ? 1 : 0
      @num_dead    += (l.dead)        ? 1 : 0
    end
  end
  
  def shortname
    file_name.gsub /^#{info.common_path}\//, ""
  end
  
  def generate
    puts "Write #{name}"
    File.open(name, 'w') do |f|
      f.write(template("coverage.html.erb").result(binding))
    end
  end
  
  def basename(n)
    File.basename(@file_name).gsub(/[^a-zA-Z0-9]+/, "_") + ((n==0) ? "" : "_#{n}")
  end
  
  def num_living
    num_lists - num_dead
  end
  
  def percent_dead
    return 0.0 if num_lists == 0
    100.0 * num_dead.to_f / num_lists
  end
  
  def percent_covered
    return 100.0 if num_living == 0
    100.0 * num_covered.to_f / num_living
  end
  
  def code
    begin
      code = File.open(file_name) { |f| f.read }
    rescue
      code = "Unable to open file #{file_name}"
    end
    add_lists_in_html(code)
  end
  
  def to_html(str)
    str = str.chr if str.respond_to?(:chr)
    str \
      .gsub("&", "&amp;") \
      .gsub("<", "&lt;") \
      .gsub(">", "&gt;") \
      .gsub(" ", "&nbsp;") \
      .gsub("\t", "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;")
  end
  
  def add_lists_in_html(code)
    code = code.lines.map { |line| line.bytes.map { |c| to_html(c) } }
    lists.each do |list|
      clas = if    list.dead?    then "dead"
             elsif list.covered? then "covered" else "not-covered" end
      code[list.line_start] = [] if code[list.line_start].nil?
      code[list.line_start][list.col_start] = "" if code[list.line_start][list.col_start].nil?
      code[list.line_end] = [] if code[list.line_end].nil?
      code[list.line_end][list.col_end] = "" if code[list.line_end][list.col_end].nil?
      code[list.line_start][list.col_start] = "<span class=\"block #{clas}\">#{code[list.line_start][list.col_start]}#{if list.covered? then "<span coveragecount=\"#{list.covered}\"></span>" end}"
      code[list.line_end][list.col_end] = "#{code[list.line_end][list.col_end]}</span>"
    end
    lineno = 0
    code.map do |line|
      lineno += 1
      "<br /><span lineno=\"#{lineno}\"></span>#{line.join}"
    end.join
  end
  
  def exists?
    File.file?(file_name)
  end
  
end

class CoverageInformation
  attr_reader :num_lists
  attr_reader :num_covered
  attr_reader :num_dead
  attr_reader :common_path

  def initialize(opts)
    @opts = opts
    @outdir = opts.output
    @files = {}
  end
  
  def is_excluded(filename)
    @opts.excludes.each do |p|
      return true if filename.match p
    end
    return false
  end

  def parse(file, filename)
    lineno = 0
    current_file = nil
    file.lines.each do |line|
      lineno += 1
      puts "...On the #{lineno}th line in #{filename}" if (lineno % 100000) == 0
      next if line[0,1] == "#"
      if line.start_with? "FILE:"
        current_file = line[/^FILE:(.*)$/, 1]
        if is_excluded(current_file) then
          current_file = nil
        elsif @files[current_file].nil? then
          @files[current_file] = CovFile.new(self, current_file)
        end
      elsif not current_file.nil? and line.start_with? "LIST:"
        m = line.match /LIST:([0-9]+:[0-9]+:[0-9]+:[0-9]+)/
        @files[current_file].list(m[1])
      elsif not current_file.nil? and line.start_with? "COVERAGE:"
        m = line.match /COVERAGE:([0-9]+):([0-9]+:[0-9]+:[0-9]+:[0-9]+)/
        @files[current_file].list(m[2]).add_coverage(m[1].to_i)
      end
    end
  end

  def files
    @files.values
  end
  
  def compute
    @num_lists   = 0
    @num_covered = 0
    @num_dead    = 0
    files.each do |f|
      f.compute
      @num_lists   += f.num_lists
      @num_covered += f.num_covered
      @num_dead    += f.num_dead
    end
  end
  
  def generate_common_path
    common = nil
    files.each do |f|
      next unless f.exists?
      if common.nil? then
        common = f.file_name.split '/'
      else
        a = f.file_name.split '/'
        common.each_index do |i|
          common.slice!(i..common.length) unless common[i] == a[i]
        end
      end
    end
    common.join '/'
  end
  
  def generate
    @common_path = generate_common_path
    basenames = []
    FileUtils.mkdir_p @outdir
    puts "Write #{@outdir}/style.css"
    FileUtils.cp find_template("style.css"), @outdir
    puts "Write #{@outdir}/jquery.js"
    FileUtils.cp find_template("jquery.js"), @outdir
    files.each do |f|
      n = 0
      while basenames.include?(f.basename(n)) do
        n += 1
      end
      f.url = "coverage_#{f.basename(n)}.html"
      f.name = "#{@outdir}/#{f.url}"
      f.generate
    end
    puts "Write #{@outdir}/index.html"
    File.open("#{@outdir}/index.html", 'w') do |f|
      f.write(template("index.html.erb").result(binding))
    end
  end
  
  def num_living
    num_lists - num_dead
  end
  
  def percent_dead
    return 0.0 if num_lists == 0
    100.0 * num_dead.to_f / num_lists
  end
  
  def percent_covered
    return 100.0 if num_living == 0
    100.0 * num_covered.to_f / num_living
  end

end

def find_template(filename)
  self_dir = File.dirname(__FILE__)
  ["#{self_dir}/#{filename}", "#{self_dir}/templates/#{filename}"].each do |f|
    return f if File.file?(f)
  end
  return nil
end

def template(filename)
  f = find_template(filename)
  ERB.new(File.open(f) { |f| f.read }, nil, "%<>")
end

def progresscolor(percent)
  middle = 90.0
  if percent < middle
    rate = percent / middle
    "rgb(255, #{(256 * rate).to_i}, 0)"
  elsif percent == middle
    "rgb(128, 128, 0)"
  else
    rate = (100.0 - percent) / (100.0 - middle)
    "rgb(#{(256 * rate).to_i}, #{(128 + 128 * rate).to_i}, 0)"
  end
end

args = opts.parse(ARGV)
info = CoverageInformation.new(options)

args.each do |filename|
  if filename == "-" then
    info.parse($stdin, "<stdin>")
  else
    File.open(filename, "r") do |f|
      info.parse(f, filename)
    end
  end
end

info.compute
info.generate


